# Generated by Django 3.2.8 on 2022-06-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantname', models.CharField(max_length=50)),
                ('foodname', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('rating', models.FloatField()),
                ('food_image', models.ImageField(upload_to='swiggy/images')),
            ],
        ),
    ]
