# Generated by Django 3.2.8 on 2022-06-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiggy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='food_image',
            field=models.ImageField(default='', upload_to='swiggy/images'),
        ),
    ]
