# Generated by Django 3.2.8 on 2022-06-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiggy', '0004_alter_item_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='food_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
