# Generated by Django 3.2.8 on 2022-06-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiggy', '0005_item_food_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='food_id',
        ),
    ]
