# Generated by Django 3.2.8 on 2022-06-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiggy', '0006_remove_item_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='foodid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
